[project]
name = "lab-cosine-similarity"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "dotenv>=0.9.9",
    "numpy>=2.3.1",
    "openai>=1.97.0",
    "scikit-learn>=1.7.0",
    "sentence-transformers>=5.0.0",
]
